// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EndpointsTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PostMethodFeature")]
    public partial class PostMethodFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PostMethodFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PostMethodFeature", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a book")]
        [NUnit.Framework.CategoryAttribute("validData")]
        [NUnit.Framework.TestCaseAttribute("Book1", null)]
        [NUnit.Framework.TestCaseAttribute("Book4", null)]
        [NUnit.Framework.TestCaseAttribute("maxInt", null)]
        [NUnit.Framework.TestCaseAttribute("withoutDescription", null)]
        [NUnit.Framework.TestCaseAttribute("author30Chars", null)]
        [NUnit.Framework.TestCaseAttribute("title100Chars", null)]
        public virtual void AddABook(string book, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "validData"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a book", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.When(string.Format("Add book {0}", book), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.Then(string.Format("Book {0} must be save", book), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book with existing id")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        public virtual void АddABookWithExistingId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book with existing id", new string[] {
                        "invalidData"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.When("Add book Book3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.When("Add book Book3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("Must show error for Id \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book with invalid id")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        [NUnit.Framework.TestCaseAttribute("negativeId", null)]
        [NUnit.Framework.TestCaseAttribute("Book0", null)]
        [NUnit.Framework.TestCaseAttribute("floatId", null)]
        [NUnit.Framework.TestCaseAttribute("tooBigId", null)]
        [NUnit.Framework.TestCaseAttribute("withoutId", null)]
        public virtual void АddABookWithInvalidId(string book, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "invalidData"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book with invalid id", @__tags);
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.When(string.Format("Add book {0}", book), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.Then("Must show Id error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book without author")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        public virtual void АddABookWithoutAuthor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book without author", new string[] {
                        "invalidData"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.When("Add book withoutAuthor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("Must show required author error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book longer author")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        public virtual void АddABookLongerAuthor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book longer author", new string[] {
                        "invalidData"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.When("Add book author31Chars", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("Must show longer author error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book without title")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        public virtual void АddABookWithoutTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book without title", new string[] {
                        "invalidData"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.When("Add book withoutTitle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("Must show required title error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Аdd a book longer title")]
        [NUnit.Framework.CategoryAttribute("invalidData")]
        public virtual void АddABookLongerTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Аdd a book longer title", new string[] {
                        "invalidData"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
 testRunner.When("Add book title101Chars", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("Must show longer title error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
